# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8eb04eca9cfd61ee804ec9933511259d915441fe28a1d18b3f30d094811fcf545621ffc3fcdf6a7783d0a49a43084894da63cc7afc37c7f5590159d4dfd8d9d

test:
  secret_key_base: e461baa0d40ccc73175fa2d81f04e8a07c01893457e88e4b48508e106a14d8ad7d74f510510fff0589770e5b7935ca812eb7b1e1fe01ac52dd647e9259b0c3e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
